#include <glug/math/box_t.h>
#include <glug/math/box.h>
#include <glug/math/circle_t.h>
#include <glug/math/circle.h>
#include <glug/math/float.h>
#include <glug/math/line2_t.h>
#include <glug/math/line2.h>
#include <glug/math/line3_t.h>
#include <glug/math/line3.h>
#include <glug/math/mat2_t.h>
#include <glug/math/mat2.h>
#include <glug/math/plane_t.h>
#include <glug/math/plane.h>
#include <glug/math/rect_t.h>
#include <glug/math/rect.h>
#include <glug/math/sphere_t.h>
#include <glug/math/sphere.h>
#include <glug/math/triangle2_t.h>
#include <glug/math/triangle2.h>
#include <glug/math/triangle3_t.h>
#include <glug/math/triangle3.h>
#include <glug/math/vec2_t.h>
#include <glug/math/vec2.h>
#include <glug/math/vec3_t.h>
#include <glug/math/vec3.h>
#include <glug/math/vec4_t.h>
#include <glug/math/vec4.h>

#include <glug/math/version.h>
