#include <glug/math/box_t.h>
#include <glug/math/box.h>
#include <glug/math/float.h>
#include <glug/math/line_t.h>
#include <glug/math/line.h>
#include <glug/math/mat2_t.h>
#include <glug/math/mat2.h>
#include <glug/math/plane_t.h>
#include <glug/math/plane.h>
#include <glug/math/sphere_t.h>
#include <glug/math/sphere.h>
#include <glug/math/triangle_t.h>
#include <glug/math/triangle.h>
#include <glug/math/vec2_t.h>
#include <glug/math/vec2.h>
#include <glug/math/vec3_t.h>
#include <glug/math/vec3.h>
#include <glug/math/vec4_t.h>
#include <glug/math/vec4.h>

#include <glug/math/version.h>
